### PR TITLE
UI update: Bugfixes for asset viewer and asset tree

### PR DESCRIPTION
**Pull request by richturner**

### CODE REVIEW

**Comment by DonWillems** [comment]
While testing I found that when adding a new asset in view mode, the tree does not (always) expand anymore and the new asset is not selected. Because of this, it seems like nothing has happened.
AddToViewMode

This issue still occurs for me: https://github.com/openremote/openremote/issues/1458
Wouter reported is was solved, but on the test deployment (and with mobile internet) I could reproduce it consistently.

New issue I can consistently reproduce:
1. Go into modify mode
2. Change the name of an asset
3. Save (successfully)
4. Switch to a different asset by clicking it in the tree
5. A 'Discard changes' dialog pops up.
6. The changes were saved correctly, discard or cancel has no effect.

This one is fixed for me: https://github.com/openremote/openremote/issues/1459

**Comment by richturner** [comment]
REST API has a default timeout of 10s I can only reproduce these issues if I throttle my connection enough to exceed this timeout so what we can do is increase the timeout but also ensure error handling is done correctly.

**Comment by richturner** [comment]
Some of the problem(s) described above also suggest packet loss not just a slow connection. The app uses websockets which is an active connection, if there is packet loss related to this it can go undetected by the UI.

**Comment by DonWillems** [comment]
> 1. New asset not selected
> 2. When saving changes to an asset for the first time in modify, dialog appears
> 3. Discard changes dialog

@richturner 2 and 3 are fixed for me now. 1 still occurs, although I don't see the endless loading I described in 1.(4) anymore.
Here is a gif of what happens about ~20% of the time while testing:
selectNewAsset

I can't find a clear reproducable steps except add a few assets and you will see it occur. It is not related to an asset already having children or not, it can appear in both.

**Comment by DonWillems** [comment]
I tested #556 because I thought it might be solved by the changes you made here. The error described there does not occur anymore, but another issue does come up that might be interesting to look into regarding this PR (I've added info to #556 ). If you want to keep it as a separate issue, that is fine too.

**Comment by richturner** [comment]
Should now be fixed and also fixed an issue where no discard warning was shown when add button was clicked

**Comment by DonWillems** [comment]
#556 and the issues described are tested and fixed. I found two additional issues:
**Can't use browser back/forward navigation between assets.**
1. Select asset A
2. Select asset B
3. Use browser back button to go back to A
4. See URL change, but asset viewer does not show A.
5. The same goes for the forward button to go to B.

**Asset tree collapses _sometimes_ in _some_ places when adding a new asset**
This seems a likely path to reproduction:
1. Expand Asset X
2. Expand Asset Y that is on the same level as X
3. Add an asset to Y
4. X collapses

I would say this second one isn't that big of a deal, so we could save that as a separate item.

**Review by DonWillems — APPROVED** [review]

**Comment by richturner** [comment]
I couldn't reproduce the last item you added, if you can reproduce it then please create a new issue for it.

**Comment by MartinaeyNL** [comment]
Quickly went through the changes as requested by @DonWillems . The changes look fine to me.
In addition to that; I'd really like to clean up the asset page (and the asset viewer) in the future, as it's really messy.

**Pull request merged**
