### PR TITLE
Fix OpenAPI configuration to generate error-free OpenAPI spec

### PR DESCRIPTION
**Pull request by pankalog**
Had to migrate to a new branch instead of using my fork. Close the other issue if you want to.

@richturner the password OAuth flow has been also added, let me know if anything else is needed!

### CODE REVIEW

**Comment by pankalog** [comment]
@richturner it seems that the last error remaining for an error-free OpenAPI schema is about the request body from the DELETE request in `org.openremote.model.gateway.GatewayServiceResource#stopTunnel`. 

OpenAPI is very much a stickler for stuff like this, and according to the [HTTP reference](https://www.rfc-editor.org/rfc/rfc9110#name-delete), a DELETE request has "No Generally Defined Semantics". So OpenAPI is showing an error because a responseBody is included in the JSON schema: 
```
Semantic error at paths./gateway/tunnel.delete.requestBody
DELETE operations cannot have a requestBody.
```

Not really sure if you'd want to spend any amount of time on this, but just letting you know.

**Comment by MartinaeyNL** [comment]
Hey @pankalog, saw this PR of yours coming by haha
Just as a small note; you can now also use https://docs.openremote.io for referring to the OR documentation. 😉

**Comment by pankalog** [comment]
@MartinaeyNL fixed!

**Review by richturner — APPROVED** [review]
I replaced the password OAuth flow with authorizationCode as password is only available in dev mode generally as it is unsafe. Authcode is the standard flow used by users.

**Comment by pankalog** [comment]
> I replaced the password OAuth flow with authorizationCode as password is only available in dev mode generally as it is unsafe. Authcode is the standard flow used by users.

Thanks!

**Pull request merged**
