### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by wborn**

### CODE REVIEW

**Review by richturner — COMMENTED** [review]
This will cause headache for my optimisation branch, I will look to remove unused imports in that branch as there are lots of files touched in there anyway.

**Comment by wborn** [comment]
I had a look at your branch (`rich/optimisation`) but it currently doesn't seem to build.
If you fix the build issues in your branch I can change this PR so it goes into your branch instead of master. :slightly_smiling_face:

**Comment by wborn** [comment]
Now that `rich/optimisation` builds, I've rebased the PR and updated the base branch @richturner.

**Comment by wborn** [comment]
Spotless can also make sure unused imports are removed and not commited, see https://github.com/openremote/openremote/pull/1441.

**Comment by richturner** [comment]
Maybe run this with the new master branch and we can get it merged without dealing with these conflicts

**Comment by wborn** [comment]
Would be nice to get this in now. :slightly_smiling_face:

**Review by richturner — APPROVED** [review]

**Pull request merged**
