### PR TITLE
Bugfix for attribute history; data changes did not correctly update the UI.

### PR DESCRIPTION
**Pull request by MartinaeyNL**
Bugfix for #1030 .

## Breakdown of the issue
The `or-attribute-history` component was incorrectly updating / rendering the data.
I discovered the following behavior:

1. Data from the correct timestamps is fetched from the database.
2. The `_data` property gets updated, triggering a render.
3. Render takes place.
4. After render, during `updated()`, a new table is created with the new data using `this._getTableTemplate()`.
5. The `_tableTemplate` property gets updated.
6. LitElement tries to update, but we cancel it manually because of insufficient changes. (see snippet)

```typescript
 shouldUpdate(_changedProperties: PropertyValues): boolean {
        let reloadData = _changedProperties.has("period") || _changedProperties.has("toTimestamp") || _changedProperties.has("attribute");
        if (this._dataFirstLoaded && !_changedProperties.get('_loading') && !reloadData) {
            return false;
        }

// If only _tableTemplate is changed, it will return false, since nothing else is updated.
```

## Changes made
I could've included a check with `changedProperties.has('_tableTemplate')` within `shouldUpdate()`.
However, that would mean 2 updates are required for each data update.

So, I changed the `updated()` method to `willUpdate()`. See https://lit.dev/docs/components/lifecycle/#willupdate
Now the table changes **during** the same update, instead of having to trigger a 2nd render. (that initially was cancelled)

.

### CODE REVIEW

**Comment by MartinaeyNL** [comment]
Ready for review. Will keep it a draft for now, since I want to test on a deployment first.

**Comment by richturner** [comment]
@MartinaeyNL Is this still a draft or is it finished?

**Comment by richturner** [comment]
@MartinaeyNL can this be merged?

**Comment by MartinaeyNL** [comment]
Forgot that this PR existed! Thanks.
Just tested it with @DonWillems on a deployment and it's indeed ready to merge.

**Pull request merged**
