### PR TITLE
ArtNet protocol Bug Fix

### PR DESCRIPTION
**Pull request by DamienKusters**
We discovered a bug while testing OpenRemote with the protocol on a remote server.

### CODE REVIEW

**Comment by RamonPeek** [comment]
^^ The bug occurred because we were reading hardcoded data for the Json-object which is used for the Value-asset. It always prompted to R,G,B,W only, even if other values were specified in the 'required values' property. We have completely removed the hardcoded constant, and replaced it with the dynamically loaded properties from the 'required values'.

**Comment by richturner** [comment]
The `gradlew` file shouldn't be modified please make this PR only show the single file change to the protocol and then I can accept. Thanks

**Comment by DamienKusters** [comment]
Quickly reverted the gradlew file 😉 
> The `gradlew` file shouldn't be modified please make this PR only show the single file change to the protocol and then I can accept. Thanks

**Comment by richturner** [comment]
Great thanks for the quick fix

**Pull request merged**
