### PR TITLE
Added Romanian Language

### PR DESCRIPTION
**Pull request by accabog**

### CODE REVIEW

**Comment by accabog** [comment]
@richturner @DonWillems , added translations for Romanian language

**Comment by accabog** [comment]
Changed to Draft to add diacritics

**Comment by pierrekil** [comment]
Hi Alexandru, are you still working on this? Would be great to add it.

**Comment by accabog** [comment]
Hi. Yes, it's done. I have to sync with your updates. I think by the end of this week will update the PR

**Comment by accabog** [comment]
Done. Please check and merge. Thanks @pierrekil

**Comment by accabog** [comment]
Done. Thanks!

**Pull request merged**
